/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package christmas.lights.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun pepito123() {

        var christmasLight = ChristmasLights()
        christmasLight.toggle(1,1,2,2)
        var result = christmasLight.grid
        assertEquals(arrayOf(arrayOf("off","off","off"),
                             arrayOf("off","on","on"),
                             arrayOf("off","on","on")), result)
    }
}
